# config.toml - Hugo configuration for go-hugo with Docsy theme

baseURL = "https://secretvpc.github.io/go-hugo/"
title = "go-hugo Documentation Site"
# theme = "docsy"
languageCode = "en-us"
DefaultContentLanguage = "en"
enableGitInfo = true
enableRobotsTXT = true

# Required for Docsy SCSS features
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    noClasses = false
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 3

# Menu configuration
[params]
  description = "Documentation site using Hugo and Docsy"
  github_repo = "https://github.com/secretvpc/go-hugo"
  github_project_repo = "https://github.com/secretvpc/go-hugo"
  github_branch = "main"
  github_subdir = ""
  ui_default_theme = "light"

  # Enable features
  disable_comments = true
  disable_search = false
  disable_breadcrumbs = false
  disable_edit = false
  disable_lastmod = false

# Docsy theme options
#[module]
#  [[module.imports]]
#    path = "github.com/google/docsy"
#    disable = false
